#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::XamarinSlideSwitch.Resource.Attribute.isOpen = global::Sample.Resource.Attribute.isOpen;
			global::XamarinSlideSwitch.Resource.Attribute.shape = global::Sample.Resource.Attribute.shape;
			global::XamarinSlideSwitch.Resource.Attribute.themeColor = global::Sample.Resource.Attribute.themeColor;
			global::XamarinSlideSwitch.Resource.Id.circle = global::Sample.Resource.Id.circle;
			global::XamarinSlideSwitch.Resource.Id.rect = global::Sample.Resource.Id.rect;
			global::XamarinSlideSwitch.Resource.String.ApplicationName = global::Sample.Resource.String.ApplicationName;
			global::XamarinSlideSwitch.Resource.String.Hello = global::Sample.Resource.String.Hello;
			global::XamarinSlideSwitch.Resource.Styleable.slideswitch = global::Sample.Resource.Styleable.slideswitch;
			global::XamarinSlideSwitch.Resource.Styleable.slideswitch_isOpen = global::Sample.Resource.Styleable.slideswitch_isOpen;
			global::XamarinSlideSwitch.Resource.Styleable.slideswitch_shape = global::Sample.Resource.Styleable.slideswitch_shape;
			global::XamarinSlideSwitch.Resource.Styleable.slideswitch_themeColor = global::Sample.Resource.Styleable.slideswitch_themeColor;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int isOpen = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int shape = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int themeColor = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int circle = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int rect = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] slideswitch = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int slideswitch_isOpen = 1;
			
			// aapt resource value: 2
			public const int slideswitch_shape = 2;
			
			// aapt resource value: 0
			public const int slideswitch_themeColor = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
